### ISSUE TITLE
کامیت بقیه اعضای تیم؟

### ISSUE THREAD

**Issue by mhaghighat20** [Astro333/Ap_10#2]
سلام دوستان پس چرا هنوز پول ریکوئست های مربوطه رو نزدین؟
@shervinj99 @Astro333 
و همچنین اسم تون رو توی فایل 
Readme.md
 کامیت نکردین؟

**Comment by mhaghighat20** [comment]
دوستان این رو کلوز نمی کنین؟

**Comment by Astro333** [comment]
فکر کردیم باید توی برنچه خودمون اسممون رو بنویسیم. اضافه شد.
